version: '3.0'
services:
  nginx:
    container_name: nginx
    image: nginx
    networks:
      - reverseproxy
    ports:
      - 8080:80
    depends_on:
      - nodejs
    volumes:
      - ./proxy/:/etc/nginx/conf.d

  nodejs:
    container_name: nodejs
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 60s  docker-entrypoint.sh yarn start
    build: 
      dockerfile: Dockerfile
      context: .    
    networks:
      - reverseproxy
    expose:
      - 3000
    volumes:
      - ./app/:/app
      - /app/node_modules
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: mysql
    networks:
      - reverseproxy
    environment:
            MYSQL_ROOT_PASSWORD: 8tD0Etc041g!
    volumes:
      - ./database/mysqlfiles/:/var/lib/mysql
      - ./database/objects:/database/objects
      - ./database/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    expose:
      - 3306

networks:
  reverseproxy:
    driver: bridge

